FROM node:20-slim
# FROM node:20-alpine

# Create app directory and user
WORKDIR /app

# Install system dependencies
# RUN apt install python3 make g++ curl

# Create non-root user
# RUN addgroup -g 1001 -S nodejs && \
#     adduser -S nextjs -u 1001

# Set npm configuration for better network handling
RUN npm config set registry https://registry.npmjs.org/ && \
    npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-retry-maxtimeout 120000 && \
    npm config set fetch-retries 5

# Copy package files first (better layer caching)
COPY package*.json ./

# Install dependencies
RUN npm install -g @nestjs/cli
# RUN npm install --network-timeout=300000


# Copy source code (use .dockerignore to exclude unnecessary files)
COPY . .

# Change ownership to non-root user
# RUN chown -R nextjs:nodejs /app
# USER 0ade06

# Expose port
EXPOSE 3000

# Environment variables
ENV NODE_OPTIONS=--experimental-global-webcrypto
ENV PATH=/app/node_modules/.bin:$PATH
ENV NODE_ENV=development

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:3000/health || exit 1

# Development command
CMD ["npm", "run", "start:dev"]
