version: '3.8'
services:
  api:
    build: .
    container_name: course-recommender-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/course-recommender?authSource=admin
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:6.0
    container_name: course-recommender-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: course-recommender
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
